export type GalleryPhoto = {
  src: string;
  width: number;
  height: number;
  alt?: string;
  title?: string;
  year?: number;
  mediums?: string[];
  referenceImages?: {
    src: string;
    width: number;
    height: number;
    alt?: string;
  }[];
  detailImages?: {
    src: string;
    width: number;
    height: number;
    alt?: string;
  }[];
};

export type GallerySection = {
  name: string;
  slug: string;
  pieces: GalleryPhoto[];
};

export const galleryConfig: GallerySection[] = [
  {
    name: "Traditional",
    slug: "traditional",
    pieces: [
      {
        src: "/images/gallery/traditional/Abby Figure Drawing Sketch - pencil on paper (Feb 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Abby Figure Drawing Sketch",
        alt: "pencil on paper (Feb 2009)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/The Controller (full) - oil pastel on paper (circa 2009).jpg",
        width: 2048,
        height: 1536,
        year: 2009,
        title: "The Controller",
        alt: "oil pastel on paper (circa 2009)",
        mediums: ["oil pastel"],
      },
      {
        src: "/images/gallery/traditional/Basset Hound - acrylic painting on canvas (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Basset Hound",
        alt: "acrylic painting on canvas (circa 2007)",
        mediums: ["acrylic on canvas"],
      },
      {
        src: "/images/gallery/traditional/Black Ballerina - chalk on chalkboard (April 2011).jpg",
        width: 1944,
        height: 2592,
        year: 2011,
        title: "Black Ballerina",
        alt: "chalk on chalkboard (April 2011)",
        mediums: ["chalk on chalkboard"],
      },
      {
        src: "/images/gallery/traditional/Bowling Alley Conversation (censored) - colored pencil on paper (circa 2008).jpg",
        width: 2048,
        height: 1536,
        year: 2008,
        title: "Bowling Alley Conversation",
        alt: "colored pencil on paper (circa 2008)",
        mediums: ["colored pencil"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/Bowling Alley Conversation (reference) - colored pencil on paper (circa 2008).jpg",
            width: 604,
            height: 453,
            alt: "reference image of Bowling Alley Conversation - colored pencil on paper (circa 2008)",
          },
        ],
      },
      {
        src: "/images/gallery/traditional/Chiaroscuro Portrait - charcoal (2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Chiaroscuro Portrait",
        alt: "charcoal (2009)",
        mediums: ["charcoal"],
      },
      {
        src: "/images/gallery/traditional/Classmate Figure Drawing - charcoal on paper (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Classmate Figure Drawing",
        alt: "charcoal on paper (circa 2009)",
        mediums: ["charcoal"],
      },
      {
        src: "/images/gallery/traditional/Classmate Portrait - ink wash on paper (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Classmate Portrait",
        alt: "ink wash on paper (circa 2009)",
        mediums: ["ink wash"],
      },
      {
        src: "/images/gallery/traditional/Concept Sketch of Kip from The Nest Archive (Erik Perez) - pencil on paper (April 2026).jpg",
        width: 3072,
        height: 4096,
        year: 2026,
        title: "Concept Sketch of Kip from The Nest Archive (Erik Perez)",
        alt: "pencil on paper (April 2026)",
        mediums: ["graphite"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/Concept Sketch of Kip (reference 1) from The Nest Archive (Erik Perez) - pencil on paper (April 2026).png",
            width: 2726,
            height: 4096,
            alt: "reference image for Concept Sketch of Kip from The Nest Archive (Erik Perez) - pencil on paper (April 2026)",
          },
          {
            src: "/images/gallery/traditional/Concept Sketch of Kip (reference 2) from The Nest Archive (Erik Perez) - pencil on paper (April 2026).png",
            width: 1600,
            height: 1600,
            alt: "reference image for Concept Sketch of Kip from The Nest Archive (Erik Perez) - pencil on paper (April 2026)",
          },
        ],
      },
      {
        src: "/images/gallery/traditional/Corkboard Mirror Self Portrait - pencil on paper (Jan 2012).jpg",
        width: 3072,
        height: 4096,
        year: 2012,
        title: "Corkboard Mirror Self Portrait",
        alt: "pencil on paper (Jan 2012)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Cresting Angel - pencil on paper (Feb 2020).jpg",
        width: 2080,
        height: 2435,
        year: 2020,
        title: "Cresting Angel",
        alt: "pencil on paper (Feb 2020)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Dachshund Diamond (censored) - pencil and colored pencil on paper (circa 2006).jpg",
        width: 1280,
        height: 960,
        year: 2006,
        title: "Dachshund Diamond",
        alt: "pencil and colored pencil on paper (circa 2006)",
        mediums: ["pencil", "colored pencil"],
      },
      {
        src: "/images/gallery/traditional/Dorm Room Drunk - pencil on lined paper (circa 2010).jpg",
        width: 1536,
        height: 2048,
        year: 2010,
        title: "Dorm Room Drunk",
        alt: "pencil on lined paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Driveway Fish - sidewalk chalk (June 2011).jpg",
        width: 1944,
        height: 2592,
        year: 2011,
        title: "Driveway Fish",
        alt: "sidewalk chalk (June 2011)",
        mediums: ["sidewalk chalk"],
      },
      {
        src: "/images/gallery/traditional/Ducky Still Life (censored) - pencil on paper (circa 2006).jpg",
        width: 2048,
        height: 1536,
        year: 2006,
        title: "Ducky Still Life",
        alt: "pencil on paper (circa 2006)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Earthy Still Life (censored) - chalk pastel on paper (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Earthy Still Life",
        alt: "chalk pastel on paper (circa 2009)",
        mediums: ["chalk pastel"],
      },
      {
        src: "/images/gallery/traditional/Esplanades Montpellier - ballpoint pen on paper (April 2013).jpg",
        width: 3072,
        height: 4096,
        year: 2013,
        title: "Esplanades, Montpellier",
        alt: "ballpoint pen on paper (April 2013)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/traditional/Gear - oil pastel on paper (circa 2009).jpg",
        width: 2048,
        height: 1536,
        year: 2009,
        title: "Gear",
        alt: "oil pastel on paper (circa 2009)",
        mediums: ["oil pastel"],
      },
      {
        src: "/images/gallery/traditional/Golden Retriever Battle - colored pencil on paper (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Golden Retriever Battle",
        alt: "colored pencil on paper (circa 2007)",
        mediums: ["colored pencil"],
      },
      {
        src: "/images/gallery/traditional/Hairy Scary Tooth Fairy - water color and colored pencil (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Hairy Scary Tooth Fairy",
        alt: "water color and colored pencil (circa 2009)",
        mediums: ["water color", "colored pencil"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/Hairy Scary Tooth Fairy (reference) - water color and colored pencil (circa 2009).png",
            width: 600,
            height: 800,
            alt: "reference image for Hairy Scary Tooth Fairy - water color and colored pencil (circa 2009)",
          },
        ],
      },
      {
        src: "/images/gallery/traditional/Hand-heart - pencil on paper (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Hand-heart",
        alt: "pencil on paper (circa 2007)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/hanging off a couch - pencil on lined paper (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Hanging off a Couch",
        alt: "pencil on lined paper (circa 2007)",
        mediums: ["graphite"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/hanging off a couch (reference 1) - pencil on lined paper (circa 2007).jpg",
            width: 1280,
            height: 960,
            alt: "reference image for Hanging off a Couch - pencil on lined paper (circa 2007)",
          },
          {
            src: "/images/gallery/traditional/hanging off a couch (reference 2) - pencil on lined paper (circa 2007).jpg",
            width: 1280,
            height: 960,
            alt: "reference image for Hanging off a Couch - pencil on lined paper (circa 2007)",
          },
          {
            src: "/images/gallery/traditional/hanging off a couch (reference 3) - pencil on lined paper (circa 2007).jpg",
            width: 1280,
            height: 960,
            alt: "reference image for Hanging off a Couch - pencil on lined paper (circa 2007)",
          },
        ],
      },

      {
        src: "/images/gallery/traditional/15 minute study of Jimmy - crayon (2007).jpg",
        width: 3072,
        height: 4096,
        year: 2007,
        title: "15 Minute Study Of Jimmy",
        alt: "crayon (2007)",
        mediums: ["crayon"],
      },
      {
        src: "/images/gallery/traditional/Andre Eye - pencil (May 2020).jpg",
        width: 4096,
        height: 3072,
        year: 2020,
        title: "Andre Eye",
        alt: "pencil (May 2020)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Andre lawn chair - pencil (May 2020).jpg",
        width: 3072,
        height: 4096,
        year: 2020,
        title: "Andre Lawn Chair",
        alt: "pencil (May 2020)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Apple - watercolor.jpg",
        width: 3072,
        height: 4096,
        title: "Apple",
        alt: "watercolor",
        mediums: ["watercolor"],
      },
      {
        src: "/images/gallery/traditional/Baloooo - watercolor (Nov 2010).jpg",
        width: 3072,
        height: 4096,
        year: 2010,
        title: "Baloooo",
        alt: "watercolor (Nov 2010)",
        mediums: ["watercolor"],
      },
      {
        src: "/images/gallery/traditional/bee - pencil.jpg",
        width: 3072,
        height: 4096,
        title: "Bee",
        alt: "pencil",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/carnival - colored pencil.jpg",
        width: 3072,
        height: 4096,
        title: "Carnival",
        alt: "colored pencil",
        mediums: ["colored pencil"],
      },
      {
        src: "/images/gallery/traditional/Figure Drawing of Justin - crayon (Feb 2007).jpg",
        width: 3072,
        height: 4096,
        year: 2007,
        title: "Figure Drawing Of Justin",
        alt: "crayon (Feb 2007)",
        mediums: ["crayon"],
      },
      {
        src: "/images/gallery/traditional/fingers crossed - pencil.jpg",
        width: 3072,
        height: 4096,
        title: "Fingers Crossed",
        alt: "pencil",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Hawaiian Hitchhiker - pencil (Sept 2011).jpg",
        width: 3072,
        height: 4096,
        year: 2011,
        title: "Hawaiian Hitchhiker",
        alt: "pencil (Sept 2011)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Jimmy Jawn Portrait from Memory - pencil on lined paper (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Jimmy Jawn Portrait From Memory",
        alt: "pencil on lined paper (circa 2007)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Judith Portrait from photo - ballpoint pen on paper (Feb 2013).jpg",
        width: 3072,
        height: 4096,
        year: 2013,
        title: "Judith Portrait From Photo",
        alt: "ballpoint pen on paper (Feb 2013)",
        mediums: ["ballpoint pen"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/Judith Portrait from photo (reference) - ballpoint pen on paper (Feb 2013).jpg",
            width: 604,
            height: 453,
            alt: "ballpoint pen on paper (Feb 2013)",
          },
        ],
      },
      {
        src: "/images/gallery/traditional/Kitchen Still Life (censored) - charcoal on paper (circa 2009).jpg",
        width: 2048,
        height: 1536,
        year: 2009,
        title: "Kitchen Still Life",
        alt: "charcoal on paper (circa 2009)",
        mediums: ["charcoal"],
      },
      {
        src: "/images/gallery/traditional/Little Me Ballerina - water color on paper (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Little Me Ballerina",
        alt: "water color on paper (circa 2009)",
        mediums: ["water color"],
      },
      {
        src: "/images/gallery/traditional/Mango Shaped Space Still Life - pencil on paper (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Mango Shaped Space Still Life",
        alt: "pencil on paper (circa 2009)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Me and Kate Portrait (censored) - oil pastel on paper (circa 2006).jpg",
        width: 1280,
        height: 960,
        year: 2006,
        title: "Me And Kate Portrait",
        alt: "oil pastel on paper (circa 2006)",
        mediums: ["oil pastel"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/Me and Kate Portrait (reference) - oil pastel on paper (circa 2006).jpg",
            width: 600,
            height: 450,
            alt: "oil pastel on paper (circa 2006)",
          },
        ],
      },
      {
        src: "/images/gallery/traditional/Eleventh Grade Chiaroscuro Self Portrait (censored) - pencil on paper (2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Eleventh Grade Chiaroscuro Self Portrait",
        alt: "pencil on paper (2009)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Mirrors Self Portrait (censored) - water color on paper possibly (circa 2009).jpg",
        width: 1536,
        height: 2048,
        year: 2009,
        title: "Mirrors Self Portrait",
        alt: "water color on paper possibly (circa 2009)",
        mediums: ["water color possibly"],
      },
      {
        src: "/images/gallery/traditional/No dawn, no day. I'm always in this twilight - watercolor (circa 2021).jpg",
        width: 4096,
        height: 3072,
        year: 2021,
        title: "No Dawn, No Day. I'm Always In This Twilight",
        alt: "watercolor (circa 2021)",
        mediums: ["watercolor"],
      },
      {
        src: "/images/gallery/traditional/Red Panda (censored) - pencil (March 2019).JPG",
        width: 3072,
        height: 4096,
        year: 2019,
        title: "Red Panda",
        alt: "pencil (March 2019)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Pointillism (censored) - stippling pen on paper (circa 2006).jpg",
        width: 960,
        height: 1280,
        year: 2006,
        title: "Pointillism",
        alt: "stippling pen on paper (circa 2006)",
        mediums: ["stippling pen"],
      },
      {
        src: "/images/gallery/traditional/Purple Zebra - marker and colored pencil on paper (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Purple Zebra",
        alt: "marker and colored pencil on paper (circa 2007)",
        mediums: ["marker", "colored pencil"],
      },
      {
        src: "/images/gallery/traditional/sad goblin - pencil (Aug 2021).jpg",
        width: 3072,
        height: 4096,
        year: 2021,
        title: "Sad Goblin",
        alt: "pencil (Aug 2021)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Self Portrait - pencil on paper (circa 2007).jpg",
        width: 1280,
        height: 960,
        year: 2007,
        title: "Self Portrait",
        alt: "pencil on paper (circa 2007)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Shame - colored pencil, pen (Nov 2019).jpg",
        width: 3072,
        height: 4096,
        year: 2019,
        title: "Shame",
        alt: "colored pencil, pen (Nov 2019)",
        mediums: ["colored pencil", "pen"],
      },
      {
        src: "/images/gallery/traditional/Stevens' Magnolia Tree Tiles (finished) - tiles in wooden frame (circa 2010).jpg",
        width: 1024,
        height: 768,
        year: 2010,
        title: "Stevens' Magnolia Tree Tiles (finished)",
        alt: "tiles in wooden frame (circa 2010)",
        mediums: ["tiles in wooden frame"],
        detailImages: [
          {
            src: "/images/gallery/traditional/Stevens' Magnolia Tree Tiles (process) - tiles in wooden frame (circa 2010).jpg",
            width: 2048,
            height: 1536,
            alt: "tiles in wooden frame (circa 2010)",
          },
        ],
      },
      {
        src: "/images/gallery/traditional/Sunflower girl - pencil on paper (March 2026).jpg",
        width: 3456,
        height: 4608,
        year: 2026,
        title: "Sunflower Girl",
        alt: "pencil on paper (March 2026)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/Toothbrush still life (censored) - pencil on paper (circa 2006).jpg",
        width: 1280,
        height: 960,
        year: 2006,
        title: "Toothbrush Still Life",
        alt: "pencil on paper (circa 2006)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/traditional/X-Ray Dog - pencil on paper (circa 2006).jpg",
        width: 1280,
        height: 960,
        year: 2006,
        title: "X-Ray Dog",
        alt: "pencil on paper (circa 2006)",
        mediums: ["graphite"],
        referenceImages: [
          {
            src: "/images/gallery/traditional/X-Ray Dog (reference) - pencil on paper (circa 2006).png",
            width: 506,
            height: 259,
            alt: "pencil on paper (circa 2006)",
          },
        ],
      },
    ],
  },
  {
    name: "Digital",
    slug: "digital",
    pieces: [
      {
        src: "/images/gallery/digital/The Round Moon (recolor) - pencil on paper and digital recolor (Feb 2021).png",
        width: 3840,
        height: 2160,
        year: 2021,
        title: "The Round Moon (recolor)",
        alt: "pencil on paper and digital recolor (Feb 2021)",
        mediums: ["pencil", "digital recolor"],
        detailImages: [
          {
            src: "/images/gallery/traditional/The Round Moon (process 1 structure) - pencil on paper and digital recolor (Feb 2021).jpg",
            width: 4608,
            height: 2112,
            alt: "pencil on paper and digital recolor (Feb 2021)",
          },
          {
            src: "/images/gallery/traditional/The Round Moon (process 2 sketch) - pencil on paper and digital recolor (Feb 2021).jpg",
            width: 4608,
            height: 2112,
            alt: "pencil on paper and digital recolor (Feb 2021)",
          },
        ],
      },

      {
        src: "/images/gallery/digital/Banana Tophad and Cane for Kaid (Nov 2022).png",
        width: 560,
        height: 560,
        title: "Banana Tophad And Cane For Kaid (Nov 2022)",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/drawing practice - eyes on emote template.png",
        width: 2000,
        height: 2000,
        title: "Drawing Practice",
        alt: "eyes on emote template",
        mediums: ["eyes on emote template"],
      },
      {
        src: "/images/gallery/digital/korra sketch.png",
        width: 480,
        height: 480,
        title: "Korra Sketch",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/lil owl guy and signature.png",
        width: 560,
        height: 560,
        title: "Lil Owl Guy And Signature",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/Mixed Chinese-Italian Girl (July 2020).png",
        width: 480,
        height: 480,
        title: "Mixed Chinese-Italian Girl (July 2020)",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/Random Fire Demon (July 2022).png",
        width: 800,
        height: 1200,
        title: "Random Fire Demon (July 2022)",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/Trace Da Genji (Jan 2021).png",
        width: 560,
        height: 560,
        title: "Trace Da Genji (Jan 2021)",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/watermarks for failderp.png",
        width: 2000,
        height: 2000,
        title: "Watermarks For Failderp",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/watermarks for rob.png",
        width: 2000,
        height: 1000,
        title: "Watermarks For Rob",
        mediums: [],
      },
      {
        src: "/images/gallery/digital/watermarks for seb.png",
        width: 2000,
        height: 1600,
        title: "Watermarks For Seb",
        mediums: [],
      },
    ],
  },
  {
    name: "Doodles",
    slug: "doodles",
    pieces: [
      {
        src: "/images/gallery/doodles/Trapped Elephant - ballpoint pen.jpg",
        width: 3072,
        height: 4096,
        title: "Trapped Elephant",
        alt: "ballpoint pen",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Zebra sketch - ballpoint pen on napkin (April 2012).jpg",
        width: 640,
        height: 480,
        year: 2012,
        title: "Zebra Sketch",
        alt: "ballpoint pen on napkin (April 2012)",
        mediums: ["ballpoint pen on napkin"],
      },
      {
        src: "/images/gallery/doodles/Abby figure drawing - purple crayon on paper (circa 2006).jpg",
        width: 960,
        height: 1280,
        year: 2006,
        title: "Abby Figure Drawing",
        alt: "purple crayon on paper (circa 2006)",
        mediums: ["purple crayon"],
      },
      {
        src: "/images/gallery/doodles/Dragon Portrait of Dad - pen and crayon on paper (June 2012).jpg",
        width: 1944,
        height: 2592,
        year: 2012,
        title: "Dragon Portrait Of Dad",
        alt: "pen and crayon on paper (June 2012)",
        mediums: ["pen", "crayon"],
      },
      {
        src: "/images/gallery/doodles/Yeonmi Park North Korean Escapist as Dva Overwatch (color) - ballpoint pen and pencil on paper (June 2020).jpg",
        width: 3072,
        height: 4096,
        year: 2020,
        title: "Yeonmi Park North Korean Escapist As Dva Overwatch (color)",
        alt: "ballpoint pen and pencil on paper (June 2020)",
        mediums: ["ballpoint pen", "pencil"],
        detailImages: [
          {
            src: "/images/gallery/doodles/Yeonmi Park North Korean Escapist as Dva Overwatch - ballpoint pen and pencil on paper (June 2020).jpg",
            width: 2112,
            height: 3555,
            alt: "ballpoint pen and pencil on paper (June 2020)",
          },
        ],
      },
      {
        src: "/images/gallery/doodles/yes but - pencil (July 2021).jpg",
        width: 3072,
        height: 4096,
        year: 2021,
        title: "Yes But",
        alt: "pencil (July 2021)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Bowl Concepts - pencil on paper (circa 2010).jpg",
        width: 2012,
        height: 1486,
        year: 2010,
        title: "Bowl Concepts",
        alt: "pencil on paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Chicken in a Banana Suit (censored) - ballpoint pen on paper (June 2023).jpg",
        width: 2243,
        height: 2229,
        year: 2023,
        title: "Chicken In A Banana Suit",
        alt: "ballpoint pen on paper (June 2023)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Death of a Salesman Doodle - pencil on paper (circa 2010).jpg",
        width: 1288,
        height: 1450,
        year: 2010,
        title: "Death Of A Salesman Doodle",
        alt: "pencil on paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Denmark Self Portrait (unfinished) from photo - pencil on paper (circa 2012).jpg",
        width: 915,
        height: 686,
        year: 2012,
        title: "Denmark Self Portrait (unfinished) From Photo",
        alt: "pencil on paper (circa 2012)",
        mediums: ["graphite"],
        referenceImages: [
          {
            src: "/images/gallery/doodles/Denmark Self Portrait (reference) from photo - pencil on paper (circa 2012).jpg",
            width: 1483,
            height: 1949,
            alt: "pencil on paper (circa 2012)",
          },
        ],
      },
      {
        src: "/images/gallery/doodles/Dragon Head sketch - ballpoint pen on paper (April 2013).jpg",
        width: 480,
        height: 640,
        year: 2013,
        title: "Dragon Head Sketch",
        alt: "ballpoint pen on paper (April 2013)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Eye sketch (unfinished) - ballpoint pen on paper (April 2012).jpg",
        width: 480,
        height: 640,
        year: 2012,
        title: "Eye Sketch (unfinished)",
        alt: "ballpoint pen on paper (April 2012)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Fire-Breathing Dragon (full, censored) - ballpoint pen on paper (circa 2010).jpg",
        width: 1280,
        height: 1024,
        year: 2010,
        title: "Fire-Breathing Dragon (full, Censored)",
        alt: "ballpoint pen on paper (circa 2010)",
        mediums: ["ballpoint pen"],
        detailImages: [
          {
            src: "/images/gallery/doodles/Fire-Breathing Dragon (dragon detail) - ballpoint pen on paper (circa 2010).jpg",
            width: 1280,
            height: 1024,
            alt: "ballpoint pen on paper (circa 2010)",
          },
          {
            src: "/images/gallery/doodles/Fire-Breathing Dragon (fire detail) - ballpoint pen on paper (circa 2010).jpg",
            width: 1280,
            height: 1024,
            alt: "ballpoint pen on paper (circa 2010)",
          },
        ],
        referenceImages: [
          {
            src: "/images/gallery/doodles/Fire-Breathing Dragon (reference) - ballpoint pen on paper (circa 2010).jpg",
            width: 400,
            height: 352,
            alt: "ballpoint pen on paper (circa 2010)",
          },
        ],
      },
      {
        src: "/images/gallery/doodles/igloo - charcoal.jpg",
        width: 4096,
        height: 3072,
        title: "Igloo",
        alt: "charcoal",
        mediums: ["charcoal"],
      },
      {
        src: "/images/gallery/doodles/Gigi Portrait from memory - pencil on paper (March 2012).jpg",
        width: 480,
        height: 640,
        year: 2012,
        title: "Gigi Portrait From Memory",
        alt: "pencil on paper (March 2012)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Giraffe and Camel Thorn Tree Doodle - ballpoint pen on paper (March 2010).jpg",
        width: 1734,
        height: 1120,
        year: 2010,
        title: "Giraffe And Camel Thorn Tree Doodle",
        alt: "ballpoint pen on paper (March 2010)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Giraffe Mug Concept - pencil on paper (circa 2010).jpg",
        width: 1980,
        height: 1031,
        year: 2010,
        title: "Giraffe Mug Concept",
        alt: "pencil on paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Giraffe Nerd Doodle - pencil on lined paper (circa 2010).jpg",
        width: 553,
        height: 1019,
        year: 2010,
        title: "Giraffe Nerd Doodle",
        alt: "pencil on lined paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/je suis le roi - pencil.jpg",
        width: 3072,
        height: 4096,
        title: "Je Suis Le Roi",
        alt: "pencil",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Keith Portrait - ballpoint pen on paper (circa 2014).jpg",
        width: 4160,
        height: 2340,
        year: 2014,
        title: "Keith Portrait",
        alt: "ballpoint pen on paper (circa 2014)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Man-Eating Broccoli Doodle - ballpoint pen on brown paper bag (circa 2010).jpg",
        width: 1199,
        height: 1309,
        year: 2010,
        title: "Man-Eating Broccoli Doodle",
        alt: "ballpoint pen on brown paper bag (circa 2010)",
        mediums: ["ballpoint pen on brown paper bag"],
      },
      {
        src: "/images/gallery/doodles/Masked Man textured sketch -pencil on paper (Nov 2010).jpg",
        width: 1920,
        height: 2560,
        title: "Masked Man Textured Sketch -pencil On Paper (Nov 2010)",
        mediums: [],
      },
      {
        src: "/images/gallery/doodles/No-faced drunk - ballpoint pen on paper (circa 2014).jpg",
        width: 3072,
        height: 4096,
        year: 2014,
        title: "No-faced Drunk",
        alt: "ballpoint pen on paper (circa 2014)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Pit Bull Bowl Concept Doodle - pencil on paper (circa 2010).jpg",
        width: 2048,
        height: 1536,
        year: 2010,
        title: "Pit Bull Bowl Concept Doodle",
        alt: "pencil on paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Pit Bull Doodle - pencil on paper (circa 2010).jpg",
        width: 1340,
        height: 988,
        year: 2010,
        title: "Pit Bull Doodle",
        alt: "pencil on paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Still Life Doodle - pencil on paper (circa 2010).jpg",
        width: 2048,
        height: 1536,
        year: 2010,
        title: "Still Life Doodle",
        alt: "pencil on paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Suki sketch - pencil.jpg",
        width: 3072,
        height: 4096,
        title: "Suki Sketch",
        alt: "pencil",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Sulking Korean-American - charcoal on paper (Oct 2010).jpg",
        width: 1536,
        height: 2048,
        year: 2010,
        title: "Sulking Korean-American",
        alt: "charcoal on paper (Oct 2010)",
        mediums: ["charcoal"],
      },
      {
        src: "/images/gallery/doodles/Teen Titans Raven's Internal World - ballpoint pen on paper (Nov 2013).jpg",
        width: 3072,
        height: 4096,
        year: 2013,
        title: "Teen Titans Raven's Internal World",
        alt: "ballpoint pen on paper (Nov 2013)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Ten Thousand Fists by Disturbed - pen on lined paper.jpg",
        width: 3072,
        height: 4096,
        title: "Ten Thousand Fists By Disturbed",
        alt: "pen on lined paper",
        mediums: ["pen on lined paper"],
      },
      {
        src: "/images/gallery/doodles/Tipping Robot Wake-Up-And-Doodle - pencil on paper (March 2010).jpg",
        width: 1536,
        height: 2048,
        year: 2010,
        title: "Tipping Robot Wake-Up-And-Doodle",
        alt: "pencil on paper (March 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Turtle-fly (censored) - ballpoint pen on paper (June 2023).jpg",
        width: 2035,
        height: 2067,
        year: 2023,
        title: "Turtle-fly",
        alt: "ballpoint pen on paper (June 2023)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Unicycle Clown (unfinished) - charcoal on paper (circa 2010).jpg",
        width: 1536,
        height: 2048,
        year: 2010,
        title: "Unicycle Clown (unfinished)",
        alt: "charcoal on paper (circa 2010)",
        mediums: ["charcoal"],
      },
      {
        src: "/images/gallery/doodles/Foreshortened Fist  for MOMA Trip - pencil on lined paper (circa 2010).jpg",
        width: 688,
        height: 967,
        year: 2010,
        title: "Foreshortened Fist For MOMA Trip",
        alt: "pencil on lined paper (circa 2010)",
        mediums: ["graphite"],
      },
      {
        src: "/images/gallery/doodles/Angel Doodle - ballpoint pen on paper (May 2012).jpg",
        width: 640,
        height: 480,
        year: 2012,
        title: "Angel Doodle",
        alt: "ballpoint pen on paper (May 2012)",
        mediums: ["ballpoint pen"],
      },
      {
        src: "/images/gallery/doodles/Angry Korean-American Saxophonist Doodle - charcoal on lined paper (circa 2010).jpg",
        width: 2048,
        height: 1536,
        year: 2010,
        title: "Angry Korean-American Saxophonist Doodle",
        alt: "charcoal on lined paper (circa 2010)",
        mediums: ["charcoal on lined paper"],
      },
      {
        src: "/images/gallery/doodles/Attack of the Jew Fro - ballpoint pen on brown paper bag (circa 2010).jpg",
        width: 2048,
        height: 1536,
        year: 2010,
        title: "Attack Of The Jew Fro",
        alt: "ballpoint pen on brown paper bag (circa 2010)",
        mediums: ["ballpoint pen on brown paper bag"],
      },
    ],
  },
  {
    name: "Mixed Media",
    slug: "mixed-media",
    pieces: [
      // {
      //   src: "/images/gallery/mixed-media/",
      //   height: "",
      //   width: "",
      //   year: "",
      //   title: "",
      //   alt: "",
      //   mediums: [],
      //   referenceImages: [
      //     {
      //       src: "/images/gallery/mixed-media/",
      //       height: "",
      //       width: "",
      //       alt: "",
      //     }
      //   ],
      //   detailImages: [
      //     {
      //       src: "/images/gallery/mixed-media/",
      //       height: "",
      //       width: "",
      //       alt: "",
      //     }
      //   ]
      // },
      {
        src: "/images/gallery/mixed-media/Andrew's Swing Dance Duet - mullbery watercolor and ballpoint pen on paper (June 2011).jpg",
        width: 1944,
        height: 2592,
        year: 2011,
        title: "Andrew's Swing Dance Duet",
        alt: "personal summertime project - mullbery watercolor and ballpoint pen on paper (June 2011)",
        mediums: ["mulberry watercolor", "ballpoint pen"],
        referenceImages: [
          {
            src: "/images/gallery/mixed-media/Andrew's Swing Dance Duet (reference) - mullbery watercolor and ballpoint pen on paper (June 2011).jpg",
            width: 720,
            height: 720,
            alt: "photo of Andrew and his partner swing dancing at an event",
          },
        ],
        detailImages: [
          {
            src: "/images/gallery/mixed-media/Andrew's Swing Dance Duet (paint) - mullbery watercolor and ballpoint pen on paper (June 2011).jpg",
            width: 2592,
            height: 1944,
            alt: "personal summertime project reference image - paint only",
          },
        ],
      },
      {
        src: "/images/gallery/mixed-media/Backpack Strap - ballpoint pen on masking tape (circa 2009).jpg",
        width: 1280,
        height: 1024,
        year: 2009,
        title: "Backpack Strap",
        alt: "ballpoint pen on masking tape (circa 2009)",
        mediums: ["ballpoint pen"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Pain Killers - soft block carving and colored pencil on paper (March 2009).jpg",
        width: 2048,
        height: 1536,
        year: 2009,
        title: "Pain Killers",
        alt: "soft block carving and colored pencil on paper (March 2009)",
        mediums: ["soft block carving", "colored pencil"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Landscaped pathway - broken concrete (Aug 2023).jpg",
        width: 2112,
        height: 4608,
        year: 2023,
        title: "Landscaped pathway",
        alt: "broken concrete (Aug 2023)",
        mediums: ["concrete", "photography"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Heart Wings (self-portrait) - ballpoint pen on jean (circa 2012).jpg",
        width: 1536,
        height: 2048,
        year: 2012,
        title: "Heart Wings (self-portrait)",
        alt: "ballpoint pen on jean (circa 2012)",
        mediums: ["ballpoint pen"],
        referenceImages: [
          {
            src: "/images/gallery/mixed-media/Heart Wings (reference) - ballpoint pen on jean (circa 2012).jpg",
            height: 100,
            width: 170,
            alt: "reference image of Heart Wings (self-portrait) - ballpoint pen on jean (circa 2012)",
          },
        ],
        detailImages: [
          {
            src: "/images/gallery/mixed-media/Heart Wings (detail) - ballpoint pen on jean (circa 2012).jpg",
            height: 2048,
            width: 1536,
            alt: "detail image of Heart Wings (self-portrait) - ballpoint pen on jean (circa 2012)",
          },
        ],
      },
      {
        src: "/images/gallery/mixed-media/Trombone Table (detail) - acrylic paint on wood (Aug 2014).jpg",
        width: 2592,
        height: 1944,
        year: 2014,
        title: "Trombone Table (detail)",
        alt: "acrylic paint on wood (Aug 2014)",
        mediums: ["acrylic paint", "wood"],
        referenceImages: [],
        detailImages: [
          {
            src: "/images/gallery/mixed-media/Trombone Table - acrylic paint on wood (Aug 2014).jpg",
            width: 2592,
            height: 1944,
            alt: "full image of Trombone Table - acrylic paint on wood (Aug 2014)",
          },
        ],
      },
      {
        src: "/images/gallery/mixed-media/DerpSquad Mug - digital print on mug (June 2021).jpg",
        width: 2112,
        height: 4608,
        year: 2021,
        title: "DerpSquad Mug",
        alt: "digital print on mug (June 2021)",
        mediums: ["digital print"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Giraffe and the Sun (unfinished) - colored paper (circa 2010).jpg",
        width: 1350,
        height: 1672,
        year: 2010,
        title: "Giraffe and the Sun [unfinished]",
        alt: "colored paper (circa 2010)",
        mediums: ["colored paper"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Seaweed Korra - seaweed on beach sand (July 2021).jpg",
        width: 4608,
        height: 2112,
        year: 2021,
        title: "Seaweed Korra",
        alt: "seaweed on beach sand (July 2021)",
        mediums: ["seaweed", "photography"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Upcycled Wallet (censored) - computer parts (circa 2012).jpg",
        width: 640,
        height: 480,
        year: 2012,
        title: "Upcycled Wallet",
        alt: "computer parts (circa 2012)",
        mediums: ["computer parts", "photography"],
        referenceImages: [],
        detailImages: [],
      },
      {
        src: "/images/gallery/mixed-media/Spring Man - screen print on t-shirt (circa 2010).jpg",
        width: 1280,
        height: 1024,
        year: 2010,
        title: "Spring Man",
        alt: "screen print on t-shirt (circa 2010)",
        mediums: ["screen print on t-shirt"],
      },
    ],
  },
];
